### ISSUE TITLE
The product export for Mars (4.5) don't work.

### ISSUE THREAD

**Issue by UrsZeidler** [UrsZeidler/shr5rcp#217]
Currently we can not build the mac product, buckminster fails:

 [ant] The ' characters around the executable and arguments are
[ant] not part of the command.
[ant] Execute:Java13CommandLauncher: Executing '/var/lib/jenkins/tools/hudson.model.JDK/jdk-7/jre/bin/java' with arguments:
[ant] '-jar'
[ant] '/var/lib/jenkins/tools/hudson.plugins.buckminster.BuckminsterInstallation/bucky_4.2-new/buckminster/plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar'
[ant] '-application'
[ant] 'org.eclipse.equinox.p2.director'
[ant] '-repository'
[ant] 'file:/var/lib/jenkins/workspace/shr5-4.3-git/buckminster.output/de.urszeidler.shr5.product.site.feature_0.3.0-eclipse.feature/site.p2/'
[ant] '-destination'
[ant] '/var/lib/jenkins/workspace/shr5-4.3-git/buckminster.output/de.urszeidler.shr5.product.site.feature_0.3.0-eclipse.feature/shr-rcp.cocoa.macosx.x86'
[ant] '-profile'
[ant] 'shr-rcp'
[ant] '-profileProperties'
[ant] 'org.eclipse.update.install.features=true'
[ant] '-installIU'
[ant] 'de.urszeidler.shr5.rcp.product.id'
[ant] '-p2.os'
[ant] 'macosx'
[ant] '-p2.ws'
[ant] 'cocoa'
[ant] '-p2.arch'
[ant] 'x86'
[ant] '-consoleLog'
[ant] '-roaming'
[ant] 
[ant] The ' characters around the executable and arguments are
[ant] not part of the command.
[ant] Installing de.urszeidler.shr5.rcp.product.id 0.3.0.
[ant] Installation failed.
[ant] !SESSION 2015-08-03 07:51:35.305 -----------------------------------------------
[ant] eclipse.buildId=unknown
[ant] java.version=1.7.0_25
[ant] java.vendor=Oracle Corporation
[ant] BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
[ant] Framework arguments:  -application org.eclipse.equinox.p2.director -repository file:/var/lib/jenkins/workspace/shr5-4.3-git/buckminster.output/de.urszeidler.shr5.product.site.feature_0.3.0-eclipse.feature/site.p2/ -destination /var/lib/jenkins/workspace/shr5-4.3-git/buckminster.output/de.urszeidler.shr5.product.site.feature_0.3.0-eclipse.feature/shr-rcp.cocoa.macosx.x86 -profile shr-rcp -profileProperties org.eclipse.update.install.features=true -installIU de.urszeidler.shr5.rcp.product.id -p2.os macosx -p2.ws cocoa -p2.arch x86 -roaming
[ant] Command-line arguments:  -application org.eclipse.equinox.p2.director -repository file:/var/lib/jenkins/workspace/shr5-4.3-git/buckminster.output/de.urszeidler.shr5.product.site.feature_0.3.0-eclipse.feature/site.p2/ -destination /var/lib/jenkins/workspace/shr5-4.3-git/buckminster.output/de.urszeidler.shr5.product.site.feature_0.3.0-eclipse.feature/shr-rcp.cocoa.macosx.x86 -profile shr-rcp -profileProperties org.eclipse.update.install.features=true -installIU de.urszeidler.shr5.rcp.product.id -p2.os macosx -p2.ws cocoa -p2.arch x86 -consoleLog -roaming
[ant] 
[ant] !ENTRY org.eclipse.equinox.p2.director 4 1 2015-08-03 07:51:43.435
[ant] !MESSAGE Cannot complete the install because one or more required items could not be found.
[ant] !SUBENTRY 1 org.eclipse.equinox.p2.director 4 0 2015-08-03 07:51:43.435
[ant] !MESSAGE Software being installed: RCP schadowrun 0.3.0 (de.urszeidler.shr5.rcp.product.id 0.3.0)
[ant] !SUBENTRY 1 org.eclipse.equinox.p2.director 4 0 2015-08-03 07:51:43.435
[ant] !MESSAGE Missing requirement for filter properties ~= $0: de.urszeidler.shr5.rcp.product.id.executable.cocoa.macosx.x86 0.3.0 requires 'org.eclipse.equinox.launcher.cocoa.macosx 0.0.0' but it could not be found
[ant] !SUBENTRY 1 org.eclipse.equinox.p2.director 4 1 2015-08-03 07:51:43.436
[ant] !MESSAGE Cannot satisfy dependency:
[ant] !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2015-08-03 07:51:43.436
[ant] !MESSAGE From: RCP schadowrun 0.3.0 (de.urszeidler.shr5.rcp.product.id 0.3.0)
[ant] !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2015-08-03 07:51:43.436
[ant] !MESSAGE To: toolingde.urszeidler.shr5.rcp.product.id.application [0.3.0]
[ant] !SUBENTRY 1 org.eclipse.equinox.p2.director 4 1 2015-08-03 07:51:43.436
[ant] !MESSAGE Cannot satisfy dependency:
[ant] !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2015-08-03 07:51:43.437
[ant] !MESSAGE From: toolingde.urszeidler.shr5.rcp.product.id.application 0.3.0
[ant] !SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2015-08-03 07:51:43.437
[ant] !MESSAGE To: de.urszeidler.shr5.rcp.product.id.executable.cocoa.macosx.x86 [0.3.0]
[ant] Cannot complete the install because one or more required items could not be found.
[ant]  Software being installed: RCP schadowrun 0.3.0 (de.urszeidler.shr5.rcp.product.id 0.3.0)
[ant]  Missing requirement for filter properties ~= $0: de.urszeidler.shr5.rcp.product.id.executable.cocoa.macosx.x86 0.3.0 requires 'org.eclipse.equinox.launcher.cocoa.macosx 0.0.0' but it could not be found
[ant]  Cannot satisfy dependency:
[ant]   From: RCP schadowrun 0.3.0 (de.urszeidler.shr5.rcp.product.id 0.3.0)
[ant]   To: toolingde.urszeidler.shr5.rcp.product.id.application [0.3.0]
[ant]  Cannot satisfy dependency:
[ant]   From: toolingde.urszeidler.shr5.rcp.product.id.application 0.3.0
[ant]   To: de.urszeidler.shr5.rcp.product.id.executable.cocoa.macosx.x86 [0.3.0]
[ant] Application failed, log file location: /var/lib/jenkins/tools/hudson.plugins.buckminster.BuckminsterInstallation/bucky_4.2-new/buckminster/configuration/1438581096108.log
[ant] 
ERROR: org.eclipse.core.runtime.CoreException: /var/lib/jenkins/workspace/shr5-4.3-git/de.urszeidler.shr5.product.site.feature/build/product.ant:22: Java returned: 13
org.eclipse.core.runtime.CoreException: /var/lib/jenkins/workspace/shr5-4.3-git/de.urszeidler.shr5.product.site.feature/build/product.ant:22: Java returned: 13
	at org.eclipse.buckminster.ant.AntRunner.handleInvocationTargetException(AntRunner.java:167)
	at org.eclipse.buckminster.ant.AntRunner.run(AntRunner.java:322)
	at org.eclipse.buckminster.ant.actor.AntActor.internalPerform(AntActor.java:254)
	at org.eclipse.buckminster.core.actor.AbstractActor.perform(AbstractActor.java:195)
	at org.eclipse.buckminster.core.internal.actor.PerformManager$DirectActionInvocation.execute(PerformManager.java:143)
	at org.eclipse.buckminster.core.internal.actor.PerformManager.internalPerform(PerformManager.java:454)
	at org.eclipse.buckminster.core.internal.actor.PerformManager.perform(PerformManager.java:293)
	at org.eclipse.buckminster.core.internal.actor.PerformManager.perform(PerformManager.java:305)
	at org.eclipse.buckminster.core.commands.Perform.internalRun(Perform.java:108)
	at org.eclipse.buckminster.core.commands.WorkspaceCommand.run(WorkspaceCommand.java:91)
	at org.eclipse.buckminster.cmdline.AbstractCommand.basicRun(AbstractCommand.java:200)
	at org.eclipse.buckminster.cmdline.Headless.run(Headless.java:350)
	at org.eclipse.buckminster.cmdline.Headless.run(Headless.java:145)
	at org.eclipse.buckminster.cmdline.Headless.start(Headless.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: /var/lib/jenkins/workspace/shr5-4.3-git/de.urszeidler.shr5.product.site.feature/build/product.ant:22: Java returned: 13

some fast research:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=408268
https://bugs.eclipse.org/bugs/show_bug.cgi?id=407588

The progress is slow, for now, as the sun is hot here in Berlin and nice.
We need to reschedule the milestone.

**Comment by UrsZeidler** [comment]
fixed
